application: quickcanvass
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: django
  version: "1.4"
- name: MySQLdb
  version: "latest"

builtins:
- django_wsgi: on

handlers:
- url: /static/admin
  static_dir: static/admin
  expiration: '0'

# [START env_variables]
env_variables:
    CLOUDSQL_CONNECTION_NAME: quickcanvass:us-central1:quickcanvass
    CLOUDSQL_USER: root
    CLOUDSQL_PASSWORD: cos333
# [END env_variables]