# application: quickcanvass
# version: 1
# runtime: python
# api_version: 1
# threadsafe: true
# env: flex
# entrypoint: gunicorn -b :$PORT main:app

runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static/
- url: .*
  script: mysite.wsgi.application

# libraries:
# - name: django
#   version: "1.4"
# - name: MySQLdb
#   version: "latest"

# builtins:
# - django_wsgi: on

# handlers:
# - url: /static/admin
#   static_dir: static/admin
#   expiration: '0'

beta_settings:
    cloud_sql_instances: quickcanvass:us-central1:quickcanvass
    enable_app_engine_apis: true

runtime_config:
  python_version: 2

# # [START env_variables]
# env_variables:
#     CLOUDSQL_CONNECTION_NAME: quickcanvass:us-central1:quickcanvass
#     CLOUDSQL_USER: root
#     CLOUDSQL_PASSWORD: cos333
# # [END env_variables]



#entrypoint: gunicorn -b :$PORT mysite.wsgi


