# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='author',
        ),
        migrations.DeleteModel(
            name='Campaign',
        ),
    ]
