# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0004_auto_20170418_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vol_auth_campaign_ids', models.CharField(max_length=80)),
                ('netid', models.CharField(max_length=30)),
                ('is_director', models.IntegerField()),
                ('manager_auth_campaign_id', models.CharField(max_length=20)),
            ],
        ),
    ]
