# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0007_auto_20170427_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='checkut_out',
            new_name='checkout',
        ),
    ]
