# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 22:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0009_remove_campaign_deadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='targetted_years',
            new_name='targeted_years',
        ),
    ]
